site_name: UoA Discrete Systems Course



markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - footnotes
  - tables

theme: 
  name: material
  logo: assets/logo.svg
  features:
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - toc.integrate
    - navigation.top
  palette:
    primary: teal
nav: 
  - Home: index.md
  - Lecture: lecture.md 
  - Chapters:
    - 'Chapter 01: Sets': 
      - 'Introduction of Sets': chapters/c01/1_sets.md                        
  - Resource: resource.md
  - Notes and FAQ: faq.md
  - 'LMS (lecture)': 'https://elms.u-aizu.ac.jp/course/view.php?id=5221'
  - 'LMS (assigment submission)': 'https://elms.u-aizu.ac.jp/course/view.php?id=5222'
plugins:
  - search
